### ISSUE TITLE
Deploy failed, please check the repo and try again.

### ISSUE THREAD

**Issue by RPGi0** [moltin-examples/nextjs-demo-store#1]
With an activated Stripe account, a valid Moltin client secret, and an authorized Zeit API key, every attempt to deploy to Now.sh is coming back with the message "Deploy failed, please check the repo and try again."

**Comment by RPGi0** [comment]
Looks like there might be something wrong with the build out there on GitHub…

When deploying locally, the following stack trace occurs:
Cannot read property ‘main_images’ of undefined
TypeError: Cannot read property ‘main_images’ of undefined
at Object.main_images (/Users/rob/CodeWork/nextjs-demo-store/pages/index.js:13:37)

**Comment by ynnoj** [comment]
Hey @RPGi0 👋 

Sorry you were having issues! We identified and patched this issue yesterday (https://github.com/moltin-examples/nextjs-demo-store/commit/b5984e43405564de491a662207420ffd3322c5e4).

Your store should work now if you try deploy again!
