### ISSUE TITLE
Header Not Bootstrapped

### ISSUE THREAD

**Issue by Kromite** [moltin-examples/nextjs-demo-store#5]
Hello,

Upon accessing the demo and inspecting, it doesn't appear to be reacting to screen size for mobile. I have tried a few different ways. So unless it's my computer, may be worth checking out.

Edit: It is the 'Cart' button specifically.

-Jake

**Comment by notrab** [comment]
Hey,

This demo isn’t intended for production use but if you wish to submit a PR to fix the issue, I’d happily merge it in. 

Thanks
