### ISSUE TITLE
Project not working

### ISSUE THREAD

**Issue by koolamusic** [moltin-examples/nextjs-demo-store#7]
This demo does not work out of the box. 
I think the major concern could be with the webpack configuration stated in 
https://github.com/moltin/js-sdk

The Next project cannot identity @moltin/sdk

**Comment by notrab** [comment]
Hi @koolamusic 

This issue will be fixed once we merge and close https://github.com/moltin-examples/nextjs-demo-store/pull/6

**Comment by koolamusic** [comment]
alright, that sounds good to me
